unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded"

set -g prefix C-a

set -g mouse on

set -g default-terminal "tmux-256color"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Basic status line positioning and size
set-option -g status-position top
set -g focus-events on
set -g status-left-length 99
set -g status-right-length 99

# Show just window name, no index clutter
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

# Minimal status-left
set -g status-left " "

# Status-right: session name only
set -g status-right "#{E:@catppuccin_status_session}"

set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_status_background "none"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make tmux command color match catppuccin font
set -g message-style "fg=#cad3f5, bg=default"
set -g prompt-cursor-colour "#f4dbd6"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
